GET ALL CHARACTERS
GET http://localhost:8080/api/v1/characters

GET ONE CHARACTER  
GET http://localhost:8080/api/v1/characters/3

GET HELLO FOR USER  
GET http://localhost:8080/api/v1/characters/hello/user

GET HELLO FOR ADMIN  
GET http://localhost:8080/api/v1/characters/hello/admin

GET HELLO FOR UNKNOWN  
GET http://localhost:8080/api/v1/characters/hello/unknown

CREATE ONE CHARACTER  
POST http://localhost:8080/api/v1/characters  
Content-Type: application/json  

{
  "name": "John",
  "description": "Main hero of the story"
}

UPDATE ONE CHARACTER  
PUT http://localhost:8080/api/v1/characters  
Content-Type: application/json  

{
  "id": "3",
  "name": "Alice",
  "description": "Wizard with healing powers"
}

DELETE ONE CHARACTER  
DELETE http://localhost:8080/api/v1/characters/3
###
